# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbf3066b9e3c5df472ed87d9d0c07e13fdae8ab2b7f6fcd5431baf6e49f88a595221fd6518cf0c7c1c57c8258defe0ae69bf7b9a588ba8210e25a1cb5af6527b

test:
  secret_key_base: 08a918df515fc0f8692b88f8372a1102e95ec2d844b27b832164b58bf554630ea1751049793fb04cae02fee6fb3f00f132821ff3e41b2a85db98577721fc93ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
